name: Unit Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Check formatting
        run: | 
          ./gradlew ktlintCheck
      - name: Run tests
        run: |
          ./gradlew \
          :redpulsar-core:test \
          :redpulsar-jedis:test \
          :redpulsar-lettuce:test \
          -DexcludeTags="integration"

      - name: Archive JUnit Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: junit-test-results
          path: |
            redpulsar-core/build/test-results/test
            redpulsar-jedis/build/test-results/test
            redpulsar-lettuce/build/test-results/test
          retention-days: 3
